'use client';

import { useState, useRef, useCallback } from 'react';
import { Download, Code, FileJson, Film, Copy, Check } from 'lucide-react';
import { useEditorStore } from '@/store';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { cn } from '@/lib/utils';

export function ExportDialog() {
  const { project, exportProject } = useEditorStore();
  const [copied, setCopied] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [recordingProgress, setRecordingProgress] = useState(0);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const handleCopyJson = useCallback(() => {
    const json = exportProject();
    navigator.clipboard.writeText(json);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [exportProject]);

  const handleDownloadJson = useCallback(() => {
    const json = exportProject();
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project?.name || 'cracktro'}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }, [exportProject, project?.name]);

  const generateHtmlExport = useCallback(() => {
    if (!project) return '';

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      background: ${project.backgroundColor}; 
      overflow: hidden;
      width: 100vw;
      height: 100vh;
    }
    canvas {
      position: absolute;
      top: 0;
      left: 0;
    }
  </style>
</head>
<body>
  <canvas id="canvas" width="${project.width}" height="${project.height}"></canvas>
  <script>
    // Cracktro Project: ${project.name}
    // Generated by Cracktro Designer
    // Effects: ${project.effects.map(e => e.type).join(', ')}
    
    const canvas = document.getElementById('canvas');
    const ctx = canvas.getContext('2d');
    
    // Resize canvas to fit window
    function resize() {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    }
    resize();
    window.addEventListener('resize', resize);
    
    // Project data
    const projectData = ${JSON.stringify(project, null, 2)};
    
    // Animation loop
    let time = 0;
    function animate() {
      ctx.fillStyle = '${project.backgroundColor}';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      
      // Render effects based on project data
      projectData.effects.forEach(effect => {
        if (!effect.enabled) return;
        ctx.globalAlpha = effect.opacity;
        // Effect rendering would go here
        // This is a simplified export - full rendering requires the effect implementations
      });
      
      ctx.globalAlpha = 1;
      time += 0.016;
      requestAnimationFrame(animate);
    }
    
    animate();
    
    console.log('Cracktro loaded! Project:', projectData.name);
    console.log('Note: This is a simplified export. For full effect rendering,');
    console.log('use the Cracktro Designer application.');
  </script>
</body>
</html>`;
  }, [project]);

  const handleDownloadHtml = useCallback(() => {
    const html = generateHtmlExport();
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project?.name || 'cracktro'}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [generateHtmlExport, project?.name]);

  if (!project) return null;

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="w-4 h-4" />
          Export
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Export Project</DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="json" className="mt-4">
          <TabsList className="w-full grid grid-cols-3">
            <TabsTrigger value="json" className="gap-2">
              <FileJson className="w-4 h-4" />
              JSON
            </TabsTrigger>
            <TabsTrigger value="html" className="gap-2">
              <Code className="w-4 h-4" />
              HTML
            </TabsTrigger>
            <TabsTrigger value="video" className="gap-2">
              <Film className="w-4 h-4" />
              Video
            </TabsTrigger>
          </TabsList>

          <TabsContent value="json" className="space-y-4">
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <pre className="text-xs overflow-auto max-h-64 text-gray-700 dark:text-gray-300">
                {exportProject().slice(0, 500)}...
              </pre>
            </div>
            <div className="flex gap-2">
              <Button onClick={handleCopyJson} className="gap-2">
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy to Clipboard'}
              </Button>
              <Button variant="outline" onClick={handleDownloadJson} className="gap-2">
                <Download className="w-4 h-4" />
                Download JSON
              </Button>
            </div>
          </TabsContent>

          <TabsContent value="html" className="space-y-4">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Export as a standalone HTML file that can be opened in any browser.
              Note: Some advanced effects may have simplified rendering.
            </p>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <pre className="text-xs overflow-auto max-h-64 text-gray-700 dark:text-gray-300">
                {generateHtmlExport().slice(0, 500)}...
              </pre>
            </div>
            <Button onClick={handleDownloadHtml} className="gap-2">
              <Download className="w-4 h-4" />
              Download HTML
            </Button>
          </TabsContent>

          <TabsContent value="video" className="space-y-4">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Record your cracktro as a video file. This feature uses the browser&apos;s
              MediaRecorder API to capture the canvas.
            </p>
            
            {isRecording ? (
              <div className="space-y-2">
                <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                  <div
                    className="bg-purple-500 h-2 rounded-full transition-all"
                    style={{ width: `${recordingProgress}%` }}
                  />
                </div>
                <p className="text-sm text-center text-gray-500">
                  Recording... {recordingProgress}%
                </p>
              </div>
            ) : (
              <div className="text-center py-8">
                <Film className="w-12 h-12 mx-auto mb-4 text-gray-400" />
                <p className="text-sm text-gray-500 mb-4">
                  Video recording coming soon!
                </p>
                <Button disabled className="gap-2">
                  <Film className="w-4 h-4" />
                  Start Recording
                </Button>
              </div>
            )}
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
